# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mobxnative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobxnative

  target 'mobxnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobxnativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobxnative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobxnative-tvOS

  # target 'mobxnative-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTTest',
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'Picker', :path => '../node_modules/react-native-picker'
pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == "React"
target.remove_from_project
end
end
end
